apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: klibs
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: registry.jetbrains.team/p/klibs-io/containers/klibs-test
      custom:
        buildCommand: ./kotlin do jib
  local:
    useDockerCLI: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: klibs-io-backend
        remoteChart: oci://registry.jetbrains.team/p/cb/helm-charts/simple-app
        version: 0.3.4
        upgradeOnChange: true
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED}}"
          imagePullSecret: "{{.IMAGE_PULL_SECRET}}"
          applicationName: "{{.APPLICATION_NAME}}"
        valuesFiles:
          - values.base.yaml
          - values.features.yaml
profiles:
  - name: prod
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: registry.jetbrains.team/p/klibs-io/containers/klibs-prod
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/1
        value: values.prod.yaml
  - name: stage
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: registry.jetbrains.team/p/klibs-io/containers/klibs-test
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/1
        value: values.stage.yaml
  - name: feature
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: registry.jetbrains.team/p/klibs-io/containers/klibs-features
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/1
        value: values.features.yaml
  - name: kotlintoolchain
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: registry.jetbrains.team/p/klibs-io/containers/klibs-kotlin-toolchain
